name             'js-nginx'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures js-nginx'
long_description 'Installs/Configures js-nginx'
version          '0.1.0'
