name             'js-base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures js-base'
long_description 'Installs/Configures js-base'
version          '0.1.0'

depends 'yum-epel'
depends 'hostsfile', '~> 2.4.5'
