- job:
    name: app-build
    description: Build the go application
    defaults: global
    node: master
    properties:
      - build-discarder:
          days-to-keep: 2
          num-to-keep: 5

    triggers:
     - pollscm:
         cron: "* * * * *"

    scm:
     - git:
        url: https://github.com/pysysops/assessment-js.git
        skip-tag: true
        branches:
           - master

    builders:
     - shell: |
        #!/bin/bash
        set -e
        PATH=$PATH:/usr/lib/go/bin:/usr/local/go/bin/
        cd $WORKSPACE/app
        go build -o http

    publishers:
      - archive:
          artifacts: 'app/http'
          only-if-success: true

- job:
    name: app-package
    description: Package the go application
    defaults: global
    node: master
    properties:
      - build-discarder:
          days-to-keep: 2
          num-to-keep: 5

    triggers:
     - reverse:
         jobs: app-build
         result: success

    scm:
     - git:
        url: https://github.com/pysysops/assessment-js.git
        skip-tag: true
        branches:
           - master

    builders:
     - copyartifact:
         project: app-build
         filter: 'app/http'
         flatten: true
         target: rpms/SOURCES

     - shell: |
        #!/bin/bash
        set -e
        cd $WORKSPACE/rpms
        rpmbuild --define '_topdir '`pwd` --define 'BUILD_NUMBER '$BUILD_NUMBER -ba SPECS/app.spec

    publishers:
      - archive:
          artifacts: 'rpms/*.rpm'
          only-if-success: true
