name             'js-app'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures js-app'
long_description 'Installs/Configures js-app'
version          '0.1.0'
